FROM node
MAINTAINER Pierre-Eric Marchandet <pemarchandet@gmail.com>

# Import the complete app
ADD bundle /bundle


# Lanch application
# ENV PORT 3000
# ENV MONGO_URL 127.0.0.1
# ENV MONGO_OPLOG_URL 127.0.0.1
# RUN ['node', 'bundle/main.js']
#
# # Not necessary but clearer in development
# EXPOSE 3000
